// Lista curada de carreras de Latinoamérica para el dropdown del perfil.
// Es un SELECT (no texto libre) → no se puede poner algo inválido.
// "Estoy en el colegio" y "Otra / Aún no sé" al final como opciones válidas.
export const CAREERS: string[] = [
  // Ingenierías
  'Ingeniería Civil',
  'Ingeniería Civil Industrial',
  'Ingeniería Comercial',
  'Ingeniería Industrial',
  'Ingeniería en Informática',
  'Ingeniería de Software',
  'Ingeniería en Computación',
  'Ingeniería en Sistemas',
  'Ingeniería Mecánica',
  'Ingeniería Eléctrica',
  'Ingeniería Electrónica',
  'Ingeniería Mecatrónica',
  'Ingeniería Química',
  'Ingeniería Ambiental',
  'Ingeniería Biomédica',
  'Ingeniería en Telecomunicaciones',
  'Ingeniería de Minas',
  'Ingeniería en Construcción',
  'Ingeniería Agrónoma',
  'Ingeniería en Alimentos',
  // Tecnología / Datos
  'Ciencia de Datos',
  'Analista Programador',
  'Ciberseguridad',
  // Salud
  'Medicina',
  'Enfermería',
  'Odontología',
  'Kinesiología',
  'Nutrición y Dietética',
  'Obstetricia',
  'Tecnología Médica',
  'Fonoaudiología',
  'Terapia Ocupacional',
  'Química y Farmacia',
  'Medicina Veterinaria',
  'Psicología',
  // Ciencias
  'Biología',
  'Bioquímica',
  'Biotecnología',
  'Química',
  'Física',
  'Matemáticas',
  'Geología',
  'Astronomía',
  // Negocios / Economía
  'Administración de Empresas',
  'Contabilidad / Contador Auditor',
  'Economía',
  'Marketing',
  'Negocios Internacionales',
  'Recursos Humanos',
  'Finanzas',
  // Derecho / Sociales / Humanidades
  'Derecho',
  'Ciencia Política',
  'Relaciones Internacionales',
  'Sociología',
  'Trabajo Social',
  'Antropología',
  'Historia',
  'Filosofía',
  'Geografía',
  // Comunicación
  'Periodismo',
  'Comunicación Social',
  'Publicidad',
  'Relaciones Públicas',
  'Cine y Audiovisual',
  // Arte / Diseño / Arquitectura
  'Arquitectura',
  'Diseño Gráfico',
  'Diseño Industrial',
  'Diseño de Vestuario',
  'Artes Visuales',
  'Música',
  'Actuación / Teatro',
  // Educación
  'Educación Parvularia',
  'Pedagogía en Educación Básica',
  'Pedagogía en Educación Media',
  'Pedagogía en Educación Física',
  'Educación Diferencial',
  // Otros
  'Gastronomía',
  'Turismo',
  'Traducción / Idiomas',
  'Agronomía',
  // Comodines válidos
  'Estoy en el colegio',
  'Otra / Aún no sé',
]
